before_script:
  - git config user.name "Gitlab CI <> DILS"
  - git config user.email "gitlab-ci-client@dils.com"

stages:
    - staging
    - production

staging:
    type: deploy
    stage: staging
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_APP.git || true
        - git push -f heroku HEAD:master
    only:
        - develop

production:
    type: deploy
    stage: production
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROD_APP.git || true
        - git push -f heroku HEAD:master
    only:
        - master
